---
title: "My Paper Title"
short-title: "My Paper Running Title"
author:
  - first: Adam
    first-init: A.
    last: Ahen
    marker: '1,2'
    footnote-id: 1
    email: foo@bar.com
  - first: Brett
    first-init: B.
    last: Berger
    marker: 2
    footnote-id: 2
  - first: Carl
    first-init: C.
    last: Camp
    marker: 3
  - first: David
    first-init: D.
    last: Dodge
    marker: 3
footnote:
  - content: Corresponding author
    type: corresp
    id: 1
  - content: Another footnote.
    id: 2
affiliation:
  - institution: University of Achievement
    prefix: Department A
    country: Country A
    marker: 1
  - institution: Institution B
    country: Country B
    marker: 2
  - institution: Institution C
    country: Country C
    marker: 3
classoption:
  - letterpaper
  - inpress
# - linenumber  # uncomment to add line numbers for submission
## preamble: |
##   \usepackage{...}  # additional LaTeX packages if needed
abstract: |
  This article presents a classification of disease severity for
  patients with cystic fibrosis (CF). CF is a genetic disease that
  dramatically decreases life expectancy and quality.
keywords:
  - conditional distribution
  - cystic fibrosis
  - Kullback--Leibler divergence
  - MCMC
  - quantiles
bibliography: bibliography.bib
format:
  jds-pdf:
    keep-tex: true
  jds-html: default
---

# Equations

Weibull distribution has the virtue of being a mathematically tractable model
and is versatile in terms of its applications in reliability, life data
analysis, actuarial science and others. Apart from being a potential model in
survival analysis and reliability engineering, it has a vast domain of other
applications.

Equations are always parts of sentences, so they need to have
appropriate punctuations. To evaluate the distribution of a normal
variable, one uses
$$
  \Pr(Z \le t) = \Phi\left(\frac{Z - \mu}{\sigma} \right),
$$ {#eq-cdf}
where $Z$ follows a $N(\mu, \sigma^2)$ distribution.
Equations can be referenced by `@eq-cdf`.
When $\mu = 0$ and $\sigma = 1$, the $Z$ in @eq-cdf
becomes a standard normal variable.

Multiline equations can be presented with the `align` environment.
For example,
\begin{align*}
  g_{\mu}(\phi) &= 0,\\
  g_{\mu}(X) &= 1.
\end{align*}

An equation that is not referenced should not be labeled. The starred
version of the `equation` and `align` are for this purpose.


# Tables

We recommend {{< latex >}} package `booktabs` for professional
looking tables. Its `\toprule` and `\bottomrule` are thicker than `\midrule`.

A professional table contains no vertical lines.


# Figures

Vector graphics do not lose clarity when being scaled. Make your
figure in PDF format when you first generate it and keep in mind its
sizes in the article to avoid over-scaling. Do not simply convert a
JPEG or PNG image to a PDF.


# Code

The document class `jdsart` provides several commands to decorate

- inline code, such as `print("Hello world!")`;
- programming language, such as {{< proglang R >}}, {{< proglang Python >}}, and
  {{< proglang C++ >}};
- software package, such as {{< pkg stats >}}, {{< pkg utils >}}.

```{r}
#| label: example-code
#| comment: ""
## Dobson (1990) Page 93: Randomized Controlled Trial:
counts <- c(18, 17, 15, 20, 10, 20, 25, 13, 12)
outcome <- gl(3, 1, 9)
treatment <- gl(3, 3)
glm.D93 <- glm(counts ~ outcome + treatment, family = poisson())
summary(glm.D93)
```


# Guide for Authors

The following requirements must be followed as closely as possible. A
technically acceptable manuscript that fails to follow these requirements may be
returned for retyping, leading to delay in publication. We only accept
submissions in PDF format. The {{< latex >}} file must be provided after the
manuscript is accepted.


## Submission of Papers

Submission of a manuscript must be the original work of the author(s) and have
not been published elsewhere or under consideration for another publication, or
a substantially similar form in any language.

Authors are encouraged to recommend three to five individuals (including their
research fields, e-mail, phone numbers and addresses) who are qualified to serve
as referees for their paper.


# Citing References

The citations are in the author-year format with the `jds` bibstyle.

Citations can be in either text or parenthesis format style.
For example, @KoenkerBassett1978 is a seminal work on quantile regression;
The Laplace distribution has applications in many fields [@Kotz2001].
Quarto converts `@key` to `\citet{key}` and `[@key]` to `\citep{key}`
for PDF output with natbib.
